name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Set dist path output
        id: set-dist-path
        run: echo "dist-path=dist" >> $GITHUB_OUTPUT

      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pysantec-dist
          path: dist/*

  publish:
      needs: build
      runs-on: ubuntu-latest
      environment: release
      steps:
        - name: Download build artifacts
          uses: actions/download-artifact@v4
          with:
            name: pysantec-dist
            path: dist

        - name: Publish to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            user: __token__
            password: ${{ secrets.PYPI_API_TOKEN }}
            # To test without releasing to live PyPI, uncomment below:
            # repository_url: https://test.pypi.org/legacy/