name: syncToGitee
run-name: "[${{ github.workflow }}] - ${{ github.event.head_commit.message }}"

on:
  push: 
  workflow_dispatch:
  
env:
  GITEE_REPOSITORY: santec-corporation-cn/PySantec
  
jobs:
  sync_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          remote_repo="https://${{ vars.GITEE_USERNAME }}:${{ secrets.GITEE_PAT }}@gitee.com/${{ env.GITEE_REPOSITORY }}.git"
          git remote add gitee "${remote_repo}"
          git push gitee -f
